"""
Русские названия районов, поселений и округов Москвы

В датасете они записаны латиницей. Написание районов сверено со статьями Википедии
«Районы Москвы» и «Поселения Москвы», включая букву «ё». Новая Москва в датасете —
это поселения и городские округа (Троицк, Щербинка), а Зеленоград — целиком округ.
Используются и в дашборде, и в подписях графиков ноутбуков.
"""

OKRUG_NAMES_RU = {
    'CAO': 'ЦАО', 'SAO': 'САО', 'SVAO': 'СВАО', 'VAO': 'ВАО', 'YuVAO': 'ЮВАО',
    'YuAO': 'ЮАО', 'YuZAO': 'ЮЗАО', 'ZAO': 'ЗАО', 'SZAO': 'СЗАО',
    'ZelAO': 'ЗелАО', 'NAO': 'НАО', 'TAO': 'ТАО',
}

DISTRICT_NAMES_RU = {
    # ЦАО
    'Arbat': 'Арбат',
    'Basmanny': 'Басманный',
    'Khamovniki': 'Хамовники',
    'Krasnoselsky': 'Красносельский',
    'Meshchansky': 'Мещанский',
    'Presnensky': 'Пресненский',
    'Tagansky': 'Таганский',
    'Tverskoy': 'Тверской',
    'Yakimanka': 'Якиманка',
    'Zamoskvorechye': 'Замоскворечье',
    # САО
    'Aeroport': 'Аэропорт',
    'Begovoy': 'Беговой',
    'Beskudnikovsky': 'Бескудниковский',
    'Dmitrovsky': 'Дмитровский',
    'Golovinsky': 'Головинский',
    'Khoroshyovsky': 'Хорошёвский',
    'Khovrino': 'Ховрино',
    'Koptevo': 'Коптево',
    'Levoberezhny': 'Левобережный',
    'Molzhaninovsky': 'Молжаниновский',
    'Savyolovsky': 'Савёловский',
    'Sokol': 'Сокол',
    'Timiryazevsky': 'Тимирязевский',
    'Voykovsky': 'Войковский',
    'Zapadnoye Degunino': 'Западное Дегунино',
    # СВАО
    'Alekseevsky': 'Алексеевский',
    'Altufyevsky': 'Алтуфьевский',
    'Babushkinsky': 'Бабушкинский',
    'Bibirevo': 'Бибирево',
    'Butyrsky': 'Бутырский',
    'Lianozovo': 'Лианозово',
    'Losinoostrovsky': 'Лосиноостровский',
    'Marfino': 'Марфино',
    'Maryina Roshcha': 'Марьина Роща',
    'Ostankinsky': 'Останкинский',
    'Otradnoye': 'Отрадное',
    'Rostokino': 'Ростокино',
    'Severnoye Medvedkovo': 'Северное Медведково',
    'Severny': 'Северный',
    'Sviblovo': 'Свиблово',
    'Yaroslavsky': 'Ярославский',
    'Yuzhnoye Medvedkovo': 'Южное Медведково',
    # ВАО
    'Bogorodskoye': 'Богородское',
    'Golyanovo': 'Гольяново',
    'Ivanovskoye': 'Ивановское',
    'Izmaylovo': 'Измайлово',
    'Kosino-Ukhtomsky': 'Косино-Ухтомский',
    'Metrogorodok': 'Метрогородок',
    'Novogireyevo': 'Новогиреево',
    'Novokosino': 'Новокосино',
    'Perovo': 'Перово',
    'Preobrazhenskoye': 'Преображенское',
    'Severnoye Izmaylovo': 'Северное Измайлово',
    'Sokolinaya Gora': 'Соколиная Гора',
    'Sokolniki': 'Сокольники',
    'Veshnyaki': 'Вешняки',
    'Vostochnoye Izmaylovo': 'Восточное Измайлово',
    'Vostochny': 'Восточный',
    # ЮАО
    'Biryulyovo Vostochnoye': 'Бирюлёво Восточное',
    'Biryulyovo Zapadnoye': 'Бирюлёво Западное',
    'Brateyevo': 'Братеево',
    'Chertanovo Severnoye': 'Чертаново Северное',
    'Chertanovo Tsentralnoye': 'Чертаново Центральное',
    'Chertanovo Yuzhnoye': 'Чертаново Южное',
    'Danilovsky': 'Даниловский',
    'Donskoy': 'Донской',
    'Moskvorechye-Saburovo': 'Москворечье-Сабурово',
    'Nagatino-Sadovniki': 'Нагатино-Садовники',
    'Nagatinsky Zaton': 'Нагатинский Затон',
    'Nagorny': 'Нагорный',
    'Orekhovo-Borisovo Severnoye': 'Орехово-Борисово Северное',
    'Orekhovo-Borisovo Yuzhnoye': 'Орехово-Борисово Южное',
    'Tsaritsyno': 'Царицыно',
    'Zyablikovo': 'Зябликово',
    # ЮЗАО
    'Akademichesky': 'Академический',
    'Cheryomushki': 'Черёмушки',
    'Gagarinsky': 'Гагаринский',
    'Konkovo': 'Коньково',
    'Kotlovka': 'Котловка',
    'Lomonosovsky': 'Ломоносовский',
    'Obruchevsky': 'Обручевский',
    'Severnoye Butovo': 'Северное Бутово',
    'Tyoply Stan': 'Тёплый Стан',
    'Yasenevo': 'Ясенево',
    'Yuzhnoye Butovo': 'Южное Бутово',
    'Zyuzino': 'Зюзино',
    # ЗАО
    'Dorogomilovo': 'Дорогомилово',
    'Fili-Davydkovo': 'Фили-Давыдково',
    'Filyovsky Park': 'Филёвский Парк',
    'Kuntsevo': 'Кунцево',
    'Mozhaysky': 'Можайский',
    'Novo-Peredelkino': 'Ново-Переделкино',
    'Ochakovo-Matveyevskoye': 'Очаково-Матвеевское',
    'Prospekt Vernadskogo': 'Проспект Вернадского',
    'Ramenki': 'Раменки',
    'Solntsevo': 'Солнцево',
    'Troparyovo-Nikulino': 'Тропарёво-Никулино',
    'Vnukovo': 'Внуково',
    # СЗАО
    'Khoroshyovo-Mnyovniki': 'Хорошёво-Мнёвники',
    'Krylatskoye': 'Крылатское',
    'Kurkino': 'Куркино',
    'Mitino': 'Митино',
    'Pokrovskoye-Streshnevo': 'Покровское-Стрешнево',
    'Severnoye Tushino': 'Северное Тушино',
    'Shchukino': 'Щукино',
    'Strogino': 'Строгино',
    'Yuzhnoye Tushino': 'Южное Тушино',
    # ЗелАО
    'Zelenograd': 'Зеленоград',
    # НАО
    'Desyonovskoye': 'Десёновское',
    'Filimonkovskoye': 'Филимонковское',
    'Kokoshkino': 'Кокошкино',
    'Marushkinskoye': 'Марушкинское',
    'Moskovsky': 'Московский',
    'Mosrentgen': 'Мосрентген',
    'Ryazanovskoye': 'Рязановское',
    'Shcherbinka': 'Щербинка',
    'Sosenskoye': 'Сосенское',
    'Vnukovskoye': 'Внуковское',
    'Voskresenskoye': 'Воскресенское',
    # ТАО
    'Kievsky': 'Киевский',
    'Klyonovskoye': 'Клёновское',
    'Krasnopakhorskoye': 'Краснопахорское',
    'Mikhaylovo-Yartsevskoye': 'Михайлово-Ярцевское',
    'Novofyodorovskoye': 'Новофёдоровское',
    'Pervomayskoye': 'Первомайское',
    'Rogovskoye': 'Роговское',
    'Shchapovskoye': 'Щаповское',
    'Troitsk': 'Троицк',
    'Voronovskoye': 'Вороновское',
}
